Repository ASSU-org/ASSU_BE, pull requests merged in 2025-09, with the labels that each got.

#60 [DEPLOY/#59] blue green 전환을 위해 deploy.sh 수정
  deploy.sh
Labels: 🚀 deploy

#63 [DEPLOY/#62] deploy.sh 수정 및 redis properties관련 문제 수정
  deploy.sh
  src/main/java/com/assu/server/global/config/RedisConfig.java
Labels: 🚀 deploy

#73 [Fix/#71] 알림 api 에러 수정
  build.gradle
  src/main/java/com/assu/server/ServerApplication.java
  src/main/java/com/assu/server/domain/deviceToken/controller/DeviceTokenController.java
  src/main/java/com/assu/server/domain/inquiry/controller/InquiryController.java
  src/main/java/com/assu/server/domain/notification/controller/NotificationController.java
  src/main/java/com/assu/server/domain/notification/dto/NotificationMessageDTO.java
  src/main/java/com/assu/server/domain/notification/entity/NotificationOutbox.java
  src/main/java/com/assu/server/domain/notification/entity/OutboxCreatedEvent.java
  src/main/java/com/assu/server/domain/notification/repository/NotificationOutboxRepository.java
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/assu/server/domain/notification/service/NotificationDispatcher.java
  src/main/java/com/assu/server/domain/notification/service/NotificationListener.java
  src/main/java/com/assu/server/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/assu/server/domain/notification/service/OutboxAfterCommitPublisher.java
  src/main/java/com/assu/server/domain/notification/service/OutboxStatusService.java
  src/main/java/com/assu/server/infra/firebase/AmqpConfig.java
  src/main/java/com/assu/server/infra/firebase/FcmClient.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: :bug: bug, :recycle: refactor

#75 [FEAT/#71] 알림 전송 메소드 분리
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandService.java
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandServiceImpl.java
  src/test/java/com/assu/server/ServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: :sparkles: feature

#78 [REFACTOR/#46] 학생 로그인 및 회원가입 SSO 기반으로 동작하도록 수정
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/auth/crypto/AesGcmSchoolCredentialEncryptor.java
  src/main/java/com/assu/server/domain/auth/crypto/SchoolCredentialEncryptor.java
  src/main/java/com/assu/server/domain/auth/crypto/StudentPasswordEncoder.java
  src/main/java/com/assu/server/domain/auth/dto/login/StudentLoginRequest.java
  src/main/java/com/assu/server/domain/auth/dto/signup/StudentSignUpRequest.java
  src/main/java/com/assu/server/domain/auth/dto/signup/StudentTokenSignUpRequest.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentAuthPayload.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentInfoPayload.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentTokenAuthPayload.java
  src/main/java/com/assu/server/domain/auth/dto/ssu/USaintAuthRequest.java
  src/main/java/com/assu/server/domain/auth/dto/ssu/USaintAuthResponse.java
  src/main/java/com/assu/server/domain/auth/entity/SSUAuth.java
  src/main/java/com/assu/server/domain/auth/security/adapter/SSUAuthAdapter.java
  src/main/java/com/assu/server/domain/auth/security/jwt/JwtUtil.java
  src/main/java/com/assu/server/domain/auth/service/LoginService.java
  src/main/java/com/assu/server/domain/auth/service/LoginServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/SSUAuthServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/SignUpService.java
  src/main/java/com/assu/server/domain/auth/service/SignUpServiceImpl.java
  src/main/java/com/assu/server/domain/user/entity/Student.java
  src/main/java/com/assu/server/global/config/ProjectConfig.java
  src/test/resources/application-test.yml
Labels: :recycle: refactor

#79 [DEPLOY] v1.2
  build.gradle
  src/main/java/com/assu/server/ServerApplication.java
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/auth/crypto/AesGcmSchoolCredentialEncryptor.java
  src/main/java/com/assu/server/domain/auth/crypto/SchoolCredentialEncryptor.java
  src/main/java/com/assu/server/domain/auth/crypto/StudentPasswordEncoder.java
  src/main/java/com/assu/server/domain/auth/dto/login/StudentLoginRequest.java
  src/main/java/com/assu/server/domain/auth/dto/signup/StudentSignUpRequest.java
  src/main/java/com/assu/server/domain/auth/dto/signup/StudentTokenSignUpRequest.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentAuthPayload.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentInfoPayload.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentTokenAuthPayload.java
  src/main/java/com/assu/server/domain/auth/dto/ssu/USaintAuthRequest.java
  src/main/java/com/assu/server/domain/auth/dto/ssu/USaintAuthResponse.java
  src/main/java/com/assu/server/domain/auth/entity/SSUAuth.java
  src/main/java/com/assu/server/domain/auth/security/adapter/SSUAuthAdapter.java
  src/main/java/com/assu/server/domain/auth/security/jwt/JwtUtil.java
  src/main/java/com/assu/server/domain/auth/service/LoginService.java
  src/main/java/com/assu/server/domain/auth/service/LoginServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/SSUAuthServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/SignUpService.java
  src/main/java/com/assu/server/domain/auth/service/SignUpServiceImpl.java
  src/main/java/com/assu/server/domain/deviceToken/controller/DeviceTokenController.java
  src/main/java/com/assu/server/domain/inquiry/controller/InquiryController.java
  src/main/java/com/assu/server/domain/notification/controller/NotificationController.java
  src/main/java/com/assu/server/domain/notification/dto/NotificationMessageDTO.java
  src/main/java/com/assu/server/domain/notification/entity/NotificationOutbox.java
  src/main/java/com/assu/server/domain/notification/entity/OutboxCreatedEvent.java
  src/main/java/com/assu/server/domain/notification/repository/NotificationOutboxRepository.java
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandService.java
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/assu/server/domain/notification/service/NotificationDispatcher.java
  src/main/java/com/assu/server/domain/notification/service/NotificationListener.java
  src/main/java/com/assu/server/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/assu/server/domain/notification/service/OutboxAfterCommitPublisher.java
  src/main/java/com/assu/server/domain/notification/service/OutboxStatusService.java
  src/main/java/com/assu/server/domain/user/entity/Student.java
  src/main/java/com/assu/server/global/config/ProjectConfig.java
  src/main/java/com/assu/server/infra/firebase/AmqpConfig.java
  src/main/java/com/assu/server/infra/firebase/FcmClient.java
  src/main/resources/application.yml
  src/test/java/com/assu/server/ServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🚀 deploy

#80 [HOTFIX] docker network external 처리
  docker-compose.yml
Labels: :bug: bug

#81 [DEPLOY] v1.2 fix docker network
  docker-compose.yml
Labels: 🚀 deploy

#87 [FIX/#86] jwt white list edit
  src/main/java/com/assu/server/domain/auth/security/jwt/JwtAuthFilter.java
  src/main/java/com/assu/server/global/config/SecurityConfig.java
Labels: :bug: bug

#90 [Refactor/#77] Notification 기능 수정
  build.gradle
  src/main/java/com/assu/server/domain/notification/controller/NotificationController.java
  src/main/java/com/assu/server/domain/notification/converter/NotificationConverter.java
  src/main/java/com/assu/server/domain/notification/dto/NotificationSettingsResponse.java
  src/main/java/com/assu/server/domain/notification/entity/NotificationType.java
  src/main/java/com/assu/server/domain/notification/repository/NotificationRepository.java
  src/main/java/com/assu/server/domain/notification/repository/NotificationSettingRepository.java
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandService.java
  src/main/java/com/assu/server/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/assu/server/domain/notification/service/NotificationQueryService.java
  src/main/java/com/assu/server/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/assu/server/infra/firebase/FcmClient.java
Labels: :recycle: refactor

#93 [REFACTOR/#89] 로그인 및 회원가입 리팩토링 / [FEAT/#92] 회원탈퇴 API
  src/main/java/com/assu/server/domain/admin/entity/Admin.java
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/auth/dto/common/UserBasicInfo.java
  src/main/java/com/assu/server/domain/auth/dto/login/LoginResponse.java
  src/main/java/com/assu/server/domain/auth/dto/signup/SignUpResponse.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentTokenAuthPayload.java
  src/main/java/com/assu/server/domain/auth/schduler/MemberCleanupScheduler.java
  src/main/java/com/assu/server/domain/auth/security/adapter/CommonAuthAdapter.java
  src/main/java/com/assu/server/domain/auth/security/adapter/SSUAuthAdapter.java
  src/main/java/com/assu/server/domain/auth/service/AuthService.java
  src/main/java/com/assu/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/LoginServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/SignUpServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/WithdrawalService.java
  src/main/java/com/assu/server/domain/auth/service/WithdrawalServiceImpl.java
  src/main/java/com/assu/server/domain/member/controller/MemberController.java
  src/main/java/com/assu/server/domain/member/converter/MemberConverter.java
  src/main/java/com/assu/server/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/assu/server/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/assu/server/domain/member/entity/Member.java
  src/main/java/com/assu/server/domain/member/repository/MemberRepository.java
  src/main/java/com/assu/server/domain/member/service/MemberService.java
  src/main/java/com/assu/server/domain/member/service/MemberServiceImpl.java
  src/main/java/com/assu/server/domain/user/entity/enums/Department.java
  src/main/java/com/assu/server/domain/user/entity/enums/Major.java
  src/main/java/com/assu/server/domain/user/entity/enums/University.java
  src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
Labels: :recycle: refactor, :sparkles: feature

#94 [DEPLOY] v1.5
  src/main/java/com/assu/server/domain/admin/entity/Admin.java
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/auth/dto/common/UserBasicInfo.java
  src/main/java/com/assu/server/domain/auth/dto/login/LoginResponse.java
  src/main/java/com/assu/server/domain/auth/dto/signup/SignUpResponse.java
  src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentTokenAuthPayload.java
  src/main/java/com/assu/server/domain/auth/schduler/MemberCleanupScheduler.java
  src/main/java/com/assu/server/domain/auth/security/adapter/CommonAuthAdapter.java
  src/main/java/com/assu/server/domain/auth/security/adapter/SSUAuthAdapter.java
  src/main/java/com/assu/server/domain/auth/service/AuthService.java
  src/main/java/com/assu/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/LoginServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/SignUpServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/WithdrawalService.java
  src/main/java/com/assu/server/domain/auth/service/WithdrawalServiceImpl.java
  src/main/java/com/assu/server/domain/member/controller/MemberController.java
  src/main/java/com/assu/server/domain/member/converter/MemberConverter.java
  src/main/java/com/assu/server/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/assu/server/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/assu/server/domain/member/entity/Member.java
  src/main/java/com/assu/server/domain/member/repository/MemberRepository.java
  src/main/java/com/assu/server/domain/member/service/MemberService.java
  src/main/java/com/assu/server/domain/member/service/MemberServiceImpl.java
  src/main/java/com/assu/server/domain/user/entity/enums/Department.java
  src/main/java/com/assu/server/domain/user/entity/enums/Major.java
  src/main/java/com/assu/server/domain/user/entity/enums/University.java
  src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
Labels: 🚀 deploy

#97 [DEPLOY] v1.5 알리고 fix & 로그인 반환 에러 수정
  src/main/java/com/assu/server/domain/auth/service/LoginServiceImpl.java
  src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/assu/server/infra/aligo/client/AligoSmsClient.java
  src/main/java/com/assu/server/infra/aligo/dto/AligoSendResponse.java
Labels: 🚀 deploy

#72 [Refactor] 채팅 api 수정
  src/main/java/com/assu/server/domain/chat/config/WebSocketConfig.java
  src/main/java/com/assu/server/domain/chat/controller/ChatController.java
  src/main/java/com/assu/server/domain/chat/converter/ChatConverter.java
  src/main/java/com/assu/server/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/assu/server/domain/chat/dto/ChatRequestDTO.java
  src/main/java/com/assu/server/domain/chat/dto/ChatResponseDTO.java
  src/main/java/com/assu/server/domain/chat/service/ChatService.java
  src/main/java/com/assu/server/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/assu/server/domain/store/entity/Store.java
  src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/assu/server/global/config/SecurityConfig.java
  src/main/java/com/assu/server/global/util/PrincipalDetails.java
  src/main/resources/application.yml
  src/test/java/com/assu/server/ServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: :recycle: refactor

#119 [FIX] logout delete 매핑 -> post 매핑
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/assu/server/global/config/SecurityConfig.java
Labels: :bug: bug

#121 [REFACTOR/#110] getStores 필터링 수정
  src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
  src/main/java/com/assu/server/domain/partnership/repository/PaperContentRepository.java
Labels: :recycle: refactor

#123 [BUG/#110] 쿼리 에러 수정
  src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
  src/main/java/com/assu/server/domain/partnership/repository/PaperContentRepository.java
Labels: :bug: bug

#124 [BUG/#110] 중복 쿼리 수정
  src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
  src/main/java/com/assu/server/domain/partnership/repository/PaperContentRepository.java
Labels: :bug: bug

#129 [Feat/#128] profile image get
  src/main/java/com/assu/server/domain/inquiry/controller/InquiryController.java
  src/main/java/com/assu/server/domain/inquiry/service/ProfileImageService.java
  src/main/java/com/assu/server/domain/inquiry/service/ProfileImageServiceImpl.java
  src/main/java/com/assu/server/infra/s3/AmazonS3Manager.java
Labels: :sparkles: feature

#132 [FEAT/#131] 전화번호 및 이메일 중복 API 추가 & Major Department 추가
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/auth/dto/verification/VerificationRequestDTO.java
  src/main/java/com/assu/server/domain/auth/service/SSUAuthServiceImpl.java
  src/main/java/com/assu/server/domain/auth/service/VerificationService.java
  src/main/java/com/assu/server/domain/auth/service/VerificationServiceImpl.java
  src/main/java/com/assu/server/domain/user/entity/enums/Department.java
  src/main/java/com/assu/server/domain/user/entity/enums/Major.java
Labels: :sparkles: feature

#150 [FEAT/#149] 학생/리뷰/건의글 신고 API 구축
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/common/entity/enums/ReportedStatus.java
  src/main/java/com/assu/server/domain/partnership/service/PaperQueryServiceImpl.java
  src/main/java/com/assu/server/domain/report/controller/ReportController.java
  src/main/java/com/assu/server/domain/report/dto/ReportRequestDTO.java
  src/main/java/com/assu/server/domain/report/dto/ReportResponseDTO.java
  src/main/java/com/assu/server/domain/report/entity/Report.java
  src/main/java/com/assu/server/domain/report/entity/enums/ReportStatus.java
  src/main/java/com/assu/server/domain/report/entity/enums/ReportTargetType.java
  src/main/java/com/assu/server/domain/report/entity/enums/ReportType.java
  src/main/java/com/assu/server/domain/report/event/ReportProcessedEvent.java
  src/main/java/com/assu/server/domain/report/exception/ReportException.java
  src/main/java/com/assu/server/domain/report/repository/ReportRepository.java
  src/main/java/com/assu/server/domain/report/service/ReportService.java
  src/main/java/com/assu/server/domain/report/service/ReportServiceImpl.java
  src/main/java/com/assu/server/domain/report/service/ReportStatusSyncService.java
  src/main/java/com/assu/server/domain/review/entity/Review.java
  src/main/java/com/assu/server/domain/review/repository/ReviewRepository.java
  src/main/java/com/assu/server/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/assu/server/domain/suggestion/entity/Suggestion.java
  src/main/java/com/assu/server/domain/suggestion/repository/SuggestionRepository.java
  src/main/java/com/assu/server/domain/suggestion/service/SuggestionServiceImpl.java
  src/main/java/com/assu/server/domain/user/entity/Student.java
  src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/assu/server/global/apiPayload/code/status/SuccessStatus.java
Labels: :sparkles: feature

#153 [DEPLOY] v.18 대기 중인 제휴 계약서, 신고 기능
  src/main/java/com/assu/server/domain/auth/controller/AuthController.java
  src/main/java/com/assu/server/domain/common/entity/enums/ReportedStatus.java
  src/main/java/com/assu/server/domain/partnership/repository/PaperRepository.java
  src/main/java/com/assu/server/domain/partnership/service/PaperQueryServiceImpl.java
  src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java
  src/main/java/com/assu/server/domain/report/controller/ReportController.java
  src/main/java/com/assu/server/domain/report/dto/ReportRequestDTO.java
  src/main/java/com/assu/server/domain/report/dto/ReportResponseDTO.java
  src/main/java/com/assu/server/domain/report/entity/Report.java
  src/main/java/com/assu/server/domain/report/entity/enums/ReportStatus.java
  src/main/java/com/assu/server/domain/report/entity/enums/ReportTargetType.java
  src/main/java/com/assu/server/domain/report/entity/enums/ReportType.java
  src/main/java/com/assu/server/domain/report/event/ReportProcessedEvent.java
  src/main/java/com/assu/server/domain/report/exception/ReportException.java
  src/main/java/com/assu/server/domain/report/repository/ReportRepository.java
  src/main/java/com/assu/server/domain/report/service/ReportService.java
  src/main/java/com/assu/server/domain/report/service/ReportServiceImpl.java
  src/main/java/com/assu/server/domain/report/service/ReportStatusSyncService.java
  src/main/java/com/assu/server/domain/review/entity/Review.java
  src/main/java/com/assu/server/domain/review/repository/ReviewRepository.java
  src/main/java/com/assu/server/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/assu/server/domain/suggestion/entity/Suggestion.java
  src/main/java/com/assu/server/domain/suggestion/repository/SuggestionRepository.java
  src/main/java/com/assu/server/domain/suggestion/service/SuggestionServiceImpl.java
  src/main/java/com/assu/server/domain/user/entity/Student.java
  src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/assu/server/global/apiPayload/code/status/SuccessStatus.java
Labels: 🚀 deploy

#156 [DEPLOY] v1.19
  src/main/java/com/assu/server/domain/auth/security/jwt/JwtAuthFilter.java
  src/main/java/com/assu/server/global/config/SecurityConfig.java
Labels: 🚀 deploy

#158 [Refactor/#157] modify apis
  src/main/java/com/assu/server/domain/partnership/repository/PaperRepository.java
  src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java
  src/main/java/com/assu/server/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/assu/server/domain/store/entity/Store.java
  src/main/java/com/assu/server/domain/store/repository/StoreRepository.java
Labels: :recycle: refactor

#168 [Develop] v1.23
  src/main/java/com/assu/server/domain/partnership/controller/PartnershipController.java
  src/main/java/com/assu/server/domain/partnership/converter/PartnershipConverter.java
  src/main/java/com/assu/server/domain/partnership/dto/PartnershipResponseDTO.java
  src/main/java/com/assu/server/domain/partnership/service/PartnershipService.java
  src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java
Labels: 🚀 deploy

#174 [Refactor/#157] 응답에 전화번호 추가
  src/main/java/com/assu/server/domain/admin/dto/AdminResponseDTO.java
  src/main/java/com/assu/server/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/assu/server/domain/map/dto/MapResponseDTO.java
  src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
  src/main/java/com/assu/server/domain/partner/dto/PartnerResponseDTO.java
  src/main/java/com/assu/server/domain/partner/service/PartnerServiceImpl.java
Labels: :recycle: refactor

#175 [DEPLOY] v1.26 응답 수정
  src/main/java/com/assu/server/domain/admin/dto/AdminResponseDTO.java
  src/main/java/com/assu/server/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/assu/server/domain/map/dto/MapResponseDTO.java
  src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
  src/main/java/com/assu/server/domain/partner/dto/PartnerResponseDTO.java
  src/main/java/com/assu/server/domain/partner/service/PartnerServiceImpl.java
  src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java
Labels: 🚀 deploy
